const products = [
    {
        id: 'product1',
        name: 'Kaze Matcha Ceremonial Grade Matcha Powder - 30 gms',
        category: 'Food and Beverage',
        price: 799,
        description: 'At Kaze Matcha, we bring you the finest ceremonial-grade matcha, sourced directly from Kagoshima, Japan, renowned for its premium tea cultivation. Our matcha is made from first flush, spring harvest leaves, ensuring a vibrant green color and smooth umami flavor in every cup.\nMatcha is a powerhouse of antioxidants, vitamins, and amino acids - making it the healthiest, swiftest transition you can make—without any compromise. It\'s the perfect alternative to coffee, delivering calm, focused energy without the jitters, keeping you refreshed throughout the day.',
        images: [
            '/images/kaze-matcha-ceremonial-1.jpg',
            '/images/kaze-matcha-ceremonial-2.jpg',
        ],
        founderId: 'kaze-matcha-founders',
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Ceremonial grade matcha from Kagoshima, Japan',
            'First flush, spring harvest leaves',
            'Vibrant green color and smooth umami flavor',
            'Rich in antioxidants, vitamins, and amino acids',
            'Perfect alternative to coffee',
            'Calm, focused energy without jitters',
            '30g pack',
        ],
        materials: ['Matcha Green Tea'],
        dimensions: '30g pack',
        careInstructions: 'Store in a cool, dry place. Reseal after opening.',
        createdAt: '2024-06-01',
    },
    {
        id: 'product2',
        name: 'Lovsy Spicy Candy',
        category: 'Food and Beverage',
        price: 199,
        description: 'Experience the perfect blend of sweetness and heat with Lovsy Spicy Candy. Made with natural ingredients and a special blend of spices, these candies are perfect for those who love a little kick in their treats.',
        images: ['/images/lovsy_spicy.jpg', '/images/lovsy_spicy2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Natural ingredients',
            'Perfect blend of sweet and spicy',
            'Great for sharing',
        ],
        materials: ['Natural extracts', 'Spices'],
        dimensions: '100g pack',
        careInstructions: 'Store in a cool, dry place',
        createdAt: '2024-06-01',
    },
    {
        id: 'product3',
        name: 'Lovsy Sweet Candy',
        category: 'Food and Beverage',
        price: 199,
        description: 'Indulge in the classic sweetness of Lovsy Sweet Candy. Made with premium ingredients, these candies are perfect for satisfying your sweet tooth.',
        images: ['/images/lovsy_sweet.jpg', '/images/lovsy_sweet2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Premium ingredients',
            'Classic sweet flavor',
            'Perfect for all ages',
        ],
        materials: ['Natural extracts', 'Sugar'],
        dimensions: '100g pack',
        careInstructions: 'Store in a cool, dry place',
        createdAt: '2024-06-01',
    },
    {
        id: 'product4',
        name: 'Lovsy Salty Candy',
        category: 'Food and Beverage',
        price: 199,
        description: 'Discover the unique taste of Lovsy Salty Candy. A perfect balance of sweet and salty flavors that will keep you coming back for more.',
        images: ['/images/lovsy_salty.jpg', '/images/lovsy_salty2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Unique sweet and salty flavor',
            'Made with natural ingredients',
            'Perfect for snacking',
        ],
        materials: ['Natural extracts', 'Sea salt'],
        dimensions: '100g pack',
        careInstructions: 'Store in a cool, dry place',
        createdAt: '2024-06-01',
    },
];

module.exports = { products };