const products = [
    {
        id: 'product1',
        name: 'Kaze Matcha Ceremonial Grade Matcha Powder - 30 gms',
        category: 'Food and Beverage',
        price: 799,
        description: 'At Kaze Matcha, we bring you the finest ceremonial-grade matcha, sourced directly from Kagoshima, Japan, renowned for its premium tea cultivation. Our matcha is made from first flush, spring harvest leaves, ensuring a vibrant green color and smooth umami flavor in every cup.\nMatcha is a powerhouse of antioxidants, vitamins, and amino acids - making it the healthiest, swiftest transition you can make—without any compromise. It\'s the perfect alternative to coffee, delivering calm, focused energy without the jitters, keeping you refreshed throughout the day.',
        images: [
            '/images/kaze-matcha-ceremonial-1.jpg',
            '/images/kaze-matcha-ceremonial-2.jpg',
        ],
        founderId: 'kaze-matcha-founders',
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Ceremonial grade matcha from Kagoshima, Japan',
            'First flush, spring harvest leaves',
            'Vibrant green color and smooth umami flavor',
            'Rich in antioxidants, vitamins, and amino acids',
            'Perfect alternative to coffee',
            'Calm, focused energy without jitters',
            '30g pack',
        ],
        materials: ['Matcha Green Tea'],
        dimensions: '30g pack',
        careInstructions: 'Store in a cool, dry place. Reseal after opening.',
        createdAt: '2024-06-01',
    },
    {
        id: 'product2',
        name: 'Sneakers',
        category: 'Fashion',
        price: 199,
        description: 'Stylish sneakers for everyday wear.',
        images: ['/images/sneakers1.jpg', '/images/sneakers2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Comfortable fit',
            'Durable materials',
            'Stylish design',
        ],
        materials: ['Canvas', 'Rubber'],
        dimensions: 'Available in sizes 6-12',
        careInstructions: 'Clean with a damp cloth',
        createdAt: '2024-06-01',
    },
    {
        id: 'product3',
        name: 'Smartwatch',
        category: 'Electronics',
        price: 199,
        description: 'A smartwatch with fitness tracking features.',
        images: ['/images/smartwatch1.jpg', '/images/smartwatch2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Fitness tracking',
            'Heart rate monitor',
            'Sleep tracking',
        ],
        materials: ['Aluminum', 'Glass'],
        dimensions: '44mm case size',
        careInstructions: 'Keep away from water',
        createdAt: '2024-06-01',
    },
    {
        id: 'product4',
        name: 'Skincare Set',
        category: 'Beauty',
        price: 199,
        description: 'A complete skincare set for glowing skin.',
        images: ['/images/skincare1.jpg', '/images/skincare2.jpg'],
        founderId: null,
        rating: 0,
        reviews: 0,
        inStock: true,
        features: [
            'Natural ingredients',
            'Suitable for all skin types',
            'Complete skincare routine',
        ],
        materials: ['Natural extracts'],
        dimensions: '5 piece set',
        careInstructions: 'Store in a cool, dry place',
        createdAt: '2024-06-01',
    },
];

module.exports = { products };